//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod tb_admin;
pub mod tb_alarm_type;
pub mod tb_check_content;
pub mod tb_check_point;
pub mod tb_device;
pub mod tb_device_check_point;
pub mod tb_device_model;
pub mod tb_device_record;
pub mod tb_project;
pub mod tb_project_check_content;
pub mod tb_role;
