//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::tb_admin::Entity as TbAdmin;
pub use super::tb_alarm_type::Entity as TbAlarmType;
pub use super::tb_check_content::Entity as TbCheckContent;
pub use super::tb_check_point::Entity as TbCheckPoint;
pub use super::tb_device::Entity as TbDevice;
pub use super::tb_device_check_point::Entity as TbDeviceCheckPoint;
pub use super::tb_device_model::Entity as TbDeviceModel;
pub use super::tb_device_record::Entity as TbDeviceRecord;
pub use super::tb_project::Entity as TbProject;
pub use super::tb_project_check_content::Entity as TbProjectCheckContent;
pub use super::tb_role::Entity as TbRole;
