//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_device")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub device_id: i32,
    pub device_name: String,
    #[sea_orm(unique)]
    pub device_no: String,
    pub project_id: i32,
    pub address: String,
    pub ip_address: String,
    pub device_model_id: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub installation_height: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 1)))")]
    pub pitch_angle: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 1)))")]
    pub azimuth_angle: Decimal,
    pub abnormal_offline_duration: i32,
    pub map_url: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub sampling_frequency: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub polarization_mode: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub shaking_amplitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub rssi: Decimal,
    pub status: i16,
    pub created_time: Option<DateTime>,
    pub updated_time: Option<DateTime>,
    pub delete_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
