//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_project")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub project_id: i32,
    pub project_name: String,
    pub unit: String,
    pub address: String,
    pub r#type: i32,
    pub introduction: String,
    pub content: String,
    pub creator: String,
    pub creator_contact: String,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub displacement_speed_horizontal_threshold: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub displacement_speed_vertical_threshold: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub convergence_threshod: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub fundamental_frequency_threshod: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub disturbance_threshod: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub cumulative_displacement_threshod: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")]
    pub collection_frequency: Decimal,
    pub status: i16,
    pub created_time: Option<DateTime>,
    pub updated_time: Option<DateTime>,
    pub delete_flag: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
